### ISSUE TITLE
Problem with network functionality

### ISSUE THREAD

**Issue by minqii** [tillhanke/QuidditchScoreboard#17]
When choosing the input folder one can without a problem choose the input folder on another pc and it even loads the correct teams in the drop down list but when selecting a team these error messages appear.
![unbenannt](https://user-images.githubusercontent.com/40029468/46615638-0434f300-cb19-11e8-8c5c-4d94d2aed2f5.PNG)

**Comment by tillhanke** [comment]
This is not a problem with the network but with your file names. please try to exclude any spaces from your filenames :"Binger Beasts.png"->"BingerBeasts.png"

**Comment by minqii** [comment]
![unbenannt](https://user-images.githubusercontent.com/40029468/46630074-5723a000-cb43-11e8-87a4-c43ac734d0ae.PNG)

**Comment by tillhanke** [comment]
that is only a distant file error... network doesnt compromise the functionality
