### ISSUE TITLE
Error while loading Team

### ISSUE THREAD

**Issue by minqii** [tillhanke/QuidditchScoreboard#18]
Around 1/3 of the teams produce this error message. All the txt files are in iso-8859-1 coding

![grafik](https://user-images.githubusercontent.com/40029468/46629600-bc769180-cb41-11e8-8b43-ca941255a83a.png)

**Comment by minqii** [comment]
Apparentely the roster list is still loaded but the well, the error msg pops up anyway

**Comment by tillhanke** [comment]
can you upload a roster list that produces that error (but please without real names)

**Comment by minqii** [comment]
And how would i send you such a roster list if i have to change all the names? It isnt the roster list anymore then or is it?

**Comment by minqii** [comment]
changed the names from real names and it still produces the error message

[DarmstadtAthenas.txt](https://github.com/tillhanke/QuidditchScoreboard/files/2464812/DarmstadtAthenas.txt)

**Comment by tillhanke** [comment]
This roster had empty lines at the end which threw the error. I will upload a new release with the fix.
