### ISSUE TITLE
Umlaut not correctly shown in OBS

### ISSUE THREAD

**Issue by minqii** [tillhanke/QuidditchScoreboard#19]
Umlaut not shown correctly even with correct coding as iso-8859-1 with notepad++. Even undid and redid the coding but it still showed the umlaut wrong.

![grafik](https://user-images.githubusercontent.com/40029468/46793181-5eb29700-cd45-11e8-8d50-7442eadd6ce7.png)

**Comment by tillhanke** [comment]
can you change encoding in OBS to iso?

**Comment by minqii** [comment]
Happens with Münster Marauders as well. 
And as well with all the player names when i show them on a foul card in OBS.

**Comment by minqii** [comment]
Okay that works with OBS just fine but now there are some weird symbols in QBS itself
![grafik](https://user-images.githubusercontent.com/40029468/46796977-3d09dd80-cd4e-11e8-8e32-b389fb567399.png)
