### ISSUE TITLE
QSB doesnt detect team right. Wheres the problem?

### ISSUE THREAD

**Issue by minqii** [tillhanke/QuidditchScoreboard#21]
![grafik](https://user-images.githubusercontent.com/40029468/49690090-79c63b00-fb2b-11e8-84e5-0ffbacbc32a1.png)
![grafik](https://user-images.githubusercontent.com/40029468/49690101-a1b59e80-fb2b-11e8-86f5-77f3493d5cb4.png)

**Comment by tillhanke** [comment]
too many empty lines maybe?
