### ISSUE TITLE
Name not shown correctly in penalty window

### ISSUE THREAD

**Issue by minqii** [tillhanke/QuidditchScoreboard#24]
![grafik](https://user-images.githubusercontent.com/40029468/49881421-a087b880-fe2e-11e8-9831-075af97867b3.png)

as title and picture says

**Comment by tillhanke** [comment]
what name? Team? or player? player might be some minor glitch...

**Comment by minqii** [comment]
The name isnt correctly shown in the drop down menu as seen in the picture

**Comment by tillhanke** [comment]
open the dropdown and make screenshot please
