### ISSUE TITLE
Snitch Catches

### ISSUE THREAD

**Issue by minqii** [tillhanke/QuidditchScoreboard#26]
![grafik](https://user-images.githubusercontent.com/40029468/49881641-273c9580-fe2f-11e8-96ee-c5be4fd47d70.png)
- would be cool if you could show the teamnames instead of team left and team rightr
- and only having first and second snitch catch is not quite enough because there might be a third in the 2nd overtime.
- Snitch Catch should only be possible to select if the time is stopped or maybe auto pause time if snitch catch is selected

**Comment by tillhanke** [comment]
ok these are multiple points. 
1 : good point forgot it, will be changed
2 : i do not know the symbols for further catches? and do you want 3-4 dial buttons or something else?
3 : can be changed and is deffo a good idea

**Comment by minqii** [comment]
1. ok
2. The notation is as following. Lets say score is 70-100 in regulation time (the normal time) and team A catches. Then the score is written as following 100*-100° and game goes into first overtime. Then the score is 130*-100° and team B catches and the score looks like this: 130*°-130°* and 2nd overtime begins. In 2nd overtime the first goal or snitch catch decides the game so the end score may be something like 160*°*-130°*° or if its just a goal it would be like 140*°*-130°*°
3. cool

**Comment by minqii** [comment]
![grafik](https://user-images.githubusercontent.com/40029468/49883234-8cde5100-fe32-11e8-8ce3-b78643254436.png)
