### ISSUE TITLE
Snitch catches 2.0

### ISSUE THREAD

**Issue by minqii** [tillhanke/QuidditchScoreboard#27]
![grafik](https://user-images.githubusercontent.com/40029468/49881788-6f5bb800-fe2f-11e8-92c0-8e9a99b81d35.png)

- you can select that both teams got the first snitch catch which is not possible :P 
- after you select a snitch catch, the score doesnt get updated automatically

**Comment by tillhanke** [comment]
you still have to think while using this app, so i dont think that the first one is a real problem... and the second one is allready changed with Comment "debugged minor things with snitch catch procedure"
