### ISSUE TITLE
Team names

### ISSUE THREAD

**Issue by minqii** [tillhanke/QuidditchScoreboard#4]
Each team name has to be put into a text file for the scoreboard.
Can't take the name from the penalty stuff because that name might change

**Comment by tillhanke** [comment]
Don't know exactly what you mean here... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by minqii** [comment]
I mean, that it would be necessary that each team name which is being pulled from the roster lists is being put out in two separate text files so that i can grab those for the scoreboard.

**Comment by minqii** [comment]
So its not a problem or a bug but another feature i would like to have :)

**Comment by tillhanke** [comment]
there are the files TeamA.txt and TeamB.txt. Cant you just use those two?

**Comment by minqii** [comment]
Uuh yea, thats enough. strange that i didnt see it
